### ISSUE TITLE
Sidebar does not update cell list unless specific cell is clicked on

### ISSUE THREAD

**Issue by iwle** [CS2103-AY1819S2-W14-3/main#68]
The sidebar of the GUI, which contains the list of cells, does not update when a `cell.putShip` command is called. However, when it is clicked on, it will update the contents.

To replicate erroneous behaviour, try the following commands:

1. In command bar, type `init s/10`
2. Type `put n/Battleship c/a1`. You will see the first cell updated.
3. Type `put n/Battleship c/c1`. You will not see the third cell updated.
4. Click on the third cell. It is now updated.

**Comment by erjillsison** [comment]
The UI currently updates because the list is an ObservableList. But it only fires change notifications when adding/removing Cells as a whole and not when changing an attribute of a Cell.

Possible fix is to have an ObservableValue (perhaps a boolean) inside the Cell that toggles everytime a change occurs (putShip or shootCell)

To initialise the list:
ObservableList\<Cell\> internalList = FXCollections.observableArrayList(cell -> new Observable[]{cell.someObservableValue})

**Comment by erjillsison** [comment]
Fixed after UI change. See #87
